### ISSUE TITLE
400 Bad Request, error: "network integration disabled"

### ISSUE THREAD

**Issue by subzer011** [Notifiarr/notifiarr#186]
my client is having trouble communicating with the site. it successfully updates the uptime but the site keeps saying failed connection with a red link icon. i have port forwarded correctly on my router. and it does work at random intervals. when checking the client log, the line below pops out...

**[ERROR] 2022/03/02 15:11:09 Sending 3 service updates to Notifiarr, event: start, buffer: 0/1000, error: return code was not 200: https://notifiarr.com/api/v1/notification/services?event=start: 400 Bad Request, error: "network integration disabled"**

i'm running the client on docker, golift/notifiarr:latest, i tried running both in host/bridge modes. same error. below is my compose...

```
    notifiarr:
        image: golift/notifiarr  
        container_name: notifiarr
        network_mode: host
        hostname: notifiarr
        environment:
            - TZ=America/New_York
            - DN_API_KEY=xxxxxxx
            - DN_SONARR_0_NAME=sonarr
            - DN_SONARR_0_URL=http://192.168.1.92:8989/
            - DN_SONARR_0_API_KEY=xxxxxxx
            - DN_RADARR_0_NAME=radarr
            - DN_RADARR_0_URL=http://192.168.1.92:7878/
            - DN_RADARR_0_API_KEY=xxxxxxx
            - DN_RADARR_1_NAME=radarr4k
            - DN_RADARR_1_URL=http://192.168.1.92:7880/
            - DN_RADARR_1_API_KEY=xxxxxxx 
        restart: unless-stopped
```
