### ISSUE TITLE
Allow defining custom header for auth

### ISSUE THREAD

**Issue by owine** [Notifiarr/notifiarr#401]
I believe the client is hard coded to use `x-webauth-user` to bypass user/pass authorization. Authelia is hard coded to populate the `Remote-User` header so it would be nice to be able to define that as the header to look at for auth.

**Comment by owine** [comment]
I am using Traefik and have not gotten header mapping to work as the above would appear to.

**Comment by davidnewhall** [comment]
While I can add the ability to change the header, I agree with the opinion in https://github.com/authelia/authelia/issues/1003 that this is the responsibility of the reverse proxy. In this case, that's Traefik. Fortunately someone opened this feature request with Traefik over 3 years ago at https://github.com/traefik/traefik/issues/6047. The solution that was provided is a plugin that can transform headers. Given what reverse proxies are meant to do, my opinion dictates this to be a mandatory configuration. Recommend installing and configuring this plugin. https://github.com/tomMoulard/htransformation

Here's an example configuration:
```yaml
- Rule:
      Name:   'Auth header rename'
      Header: 'Remote-User'
      Value:  'X-WebAuth-User'
      Type:   'Rename'
```
